-- Voxly Database Schema
-- Run this in Supabase SQL Editor

-- Required by style_profiles.style_embedding vector(1536)
create extension if not exists vector;

-- Profiles (extends auth.users)
create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  email text,
  display_name text,
  credits bigint default 50,  -- free tier daily limit
  total_credits_purchased bigint default 0,
  is_pro boolean default false,
  style_profile jsonb default '{}',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Rewrites history
create table public.rewrites (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  original_text text not null,
  rewritten_text text not null,
  tone text not null check (tone in ('professional','casual','academic','persuasive','concise')),
  style_profile_id uuid,
  tokens_used bigint default 0,
  created_at timestamptz default now()
);

-- Style profiles (for Phase 2)
create table public.style_profiles (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  name text not null,
  sample_texts text[] not null,
  style_embedding vector(1536),  -- for semantic matching
  created_at timestamptz default now()
);

-- Anonymous trial usage (no login): 5 rewrites per IP per UTC day.
-- Keyed by salted SHA-256 of the client IP; only the service_role key
-- touches this table (RLS enabled, no policies for anon/authenticated).
create table public.anon_usage (
  ip_hash text not null,
  day date not null,
  count integer not null default 0,
  updated_at timestamptz default now(),
  primary key (ip_hash, day)
);
alter table public.anon_usage enable row level security;

-- Enable RLS
alter table public.profiles enable row level security;
alter table public.rewrites enable row level security;
alter table public.style_profiles enable row level security;

-- RLS Policies
create policy "Users can read own profile"
  on public.profiles for select using (auth.uid() = id);

-- NOTE: row-level policy only decides WHICH rows are updatable.
-- Column-level grants below decide WHICH columns: client keys may only write
-- display_name / email / updated_at. credits, is_pro and
-- total_credits_purchased are service_role-only, otherwise any user could
-- grant themselves Pro via the anon key.
create policy "Users can update own profile"
  on public.profiles for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

-- Column-level grants (normalize first; service_role/postgres are unaffected).
revoke all on public.profiles from anon, authenticated;
grant select on public.profiles to authenticated;
grant update (display_name, email, updated_at) on public.profiles to authenticated;

create policy "Users can read own rewrites"
  on public.rewrites for select using (auth.uid() = user_id);

create policy "Users can insert own rewrites"
  on public.rewrites for insert with check (auth.uid() = user_id);

create policy "Users can read own style profiles"
  on public.style_profiles for select using (auth.uid() = user_id);

create policy "Users can insert own style profiles"
  on public.style_profiles for insert with check (auth.uid() = user_id);

-- Indexes
create index idx_rewrites_user_id on public.rewrites(user_id);
create index idx_rewrites_created_at on public.rewrites(created_at desc);
create index idx_style_profiles_user_id on public.style_profiles(user_id);

-- Trigger for updated_at
create function public.handle_updated_at() returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger profiles_updated_at
  before update on public.profiles
  for each row execute procedure public.handle_updated_at();

-- Auto-create a profile row on signup. Without this, a fresh Google sign-in
-- has no profiles row and /api/rewrite returns 404 'Profile not found'.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, display_name)
  values (
    new.id,
    new.email,
    coalesce(
      new.raw_user_meta_data ->> 'full_name',
      new.raw_user_meta_data ->> 'name'
    )
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
