-- Voxly Database Schema
-- Run this in Supabase SQL Editor

-- Profiles (extends auth.users)
create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  email text,
  display_name text,
  credits bigint default 50,  -- free tier daily limit
  total_credits_purchased bigint default 0,
  is_pro boolean default false,
  style_profile jsonb default '{}',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Rewrites history
create table public.rewrites (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  original_text text not null,
  rewritten_text text not null,
  tone text not null check (tone in ('professional','casual','academic','persuasive','concise')),
  style_profile_id uuid,
  tokens_used bigint default 0,
  created_at timestamptz default now()
);

-- Style profiles (for Phase 2)
create table public.style_profiles (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  name text not null,
  sample_texts text[] not null,
  style_embedding vector(1536),  -- for semantic matching
  created_at timestamptz default now()
);

-- Enable RLS
alter table public.profiles enable row level security;
alter table public.rewrites enable row level security;
alter table public.style_profiles enable row level security;

-- RLS Policies
create policy "Users can read own profile"
  on public.profiles for select using (auth.uid() = id);

create policy "Users can update own profile"
  on public.profiles for update using (auth.uid() = id);

create policy "Users can read own rewrites"
  on public.rewrites for select using (auth.uid() = user_id);

create policy "Users can insert own rewrites"
  on public.rewrites for insert with check (auth.uid() = user_id);

create policy "Users can read own style profiles"
  on public.style_profiles for select using (auth.uid() = user_id);

create policy "Users can insert own style profiles"
  on public.style_profiles for insert with check (auth.uid() = user_id);

-- Indexes
create index idx_rewrites_user_id on public.rewrites(user_id);
create index idx_rewrites_created_at on public.rewrites(created_at desc);
create index idx_style_profiles_user_id on public.style_profiles(user_id);

-- Trigger for updated_at
create function public.handle_updated_at() returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger profiles_updated_at
  before update on public.profiles
  for each row execute procedure public.handle_updated_at();
